name: multi_timer
description: "Multi Timer Plus – A powerful visual timer app for productivity and focus."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.5.2
  provider: ^6.1.4
  get_it: ^8.0.3
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.1
  flutter_screenutil: ^6.0.0-alpha.1

  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  google_mobile_ads: ^6.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  default-flavor: dev
#  assets:
#    - assets/sounds/
